version: '3.3'

volumes:
  pg:
  redis_data:

services:
  db_local:
    image: postgres:13
    env_file: .env
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

